repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 0ee178619d696787ca73d210cc191d720868c631 # frozen: v3.9.6
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: 8a48f81b6c64dcfea44b3633223084c4be58ac5f # frozen: v1.49.0
    hooks:
      - id: typos

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 65dbdb59d2f2d9c3bdc343c566821ad3319ddaa3 # frozen: v0.16.3
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
        files: ^tests/ # we won't reformat everything yet.

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --no-project --python 3.9 --with "mypy[python2]==0.961" mypy --py2 --ignore-missing-imports --scripts-are-modules --strict --cache-dir /dev/null slackroll tests
        require_serial: true
        language: system
        types_or: [pyi, python]
        pass_filenames: false
