repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: b25652612a4a3c1da8caccfca9af661db56b2c07 # frozen: v3.8.2
    hooks:
      - id: prettier

  - repo: https://github.com/crate-ci/typos
    rev: 7c572958218557a3272c2d6719629443b5cc26fd # frozen: v1.45.2
    hooks:
      - id: typos

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80 # frozen: v0.15.12
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
        files: ^tests/ # we won't reformat everything yet.

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --no-project --python 3.9 --with "mypy[python2]==0.961" mypy --py2 --ignore-missing-imports --scripts-are-modules --strict --cache-dir /dev/null slackroll tests
        require_serial: true
        language: system
        types_or: [pyi, python]
        pass_filenames: false
