#!/usr/bin/env bash
asciidoc -a linkcss - <doc-index.txt >doc/index.html
asciidoc -a linkcss - <doc-faq.txt >doc/faq.html
asciidoc -a linkcss - <doc-operations.txt >doc/operations.html
asciidoc -b docbook -d manpage - <doc-manpage.txt | xsltproc --nonet -o doc/slackroll.1 http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl -
